#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
import argparse
from ph_analysis.fc.fc_averager import FCAverager

__author__ = 'Yuji Ikeda'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-w", "--weights",
                        nargs="+",
                        type=float,
                        help="Weights for the sets of the force constants.")
    parser.add_argument("-p", "--poscars",
                        nargs="+",
                        type=str,
                        help="Filenames of POSCAR.")
    parser.add_argument("-f", "--fcs",
                        nargs="+",
                        type=str,
                        help="Filenames of FORCE_CONSTANTS.")
    args = parser.parse_args()

    if len(args.poscars) != len(args.fcs):
        print("ERROR: {}".format(__name__))
        print("len(args.poscar) must be equal to len(args.fc).")
        raise ValueError

    FCAverager(args.poscars, args.fcs, args.weights).average_fc()


if __name__ == "__main__":
    main()
